# Example configuration for Twitch Notifier

# Your Twitch Application Client ID.
# Register an application at https://dev.twitch.tv/console/apps to get one.
twitch_client_id = "YOUR_TWITCH_CLIENT_ID_HERE"

# List of Twitch streamer usernames to monitor.
streamers = [
    "hasanabi",
    "xqcow",
    # Add more streamers here
]

# Polling interval in seconds (how often to check Twitch API).
# Default is 60 seconds if not specified.
# poll_interval_seconds = 60
