# Example configuration for Twitch Notifier

# Your Twitch Application Client ID.
# Register an application at https://dev.twitch.tv/console/apps to get one.
# Use the name "twitch-notifier" for the application.
twitch_client_id = "YOUR_TWITCH_CLIENT_ID_HERE"

# Your Twitch Application Client Secret.
# Get this from the Twitch Developer Portal (same place as Client ID).
# !! Keep this secret safe - do not commit it directly to public repositories !!
twitch_client_secret = "YOUR_TWITCH_CLIENT_SECRET_HERE"

# List of Twitch streamer usernames to monitor.
streamers = [
    "hasanabi",
    "xqcow",
    # Add more streamers here
]

# Polling interval in seconds (how often to check Twitch API).
# Default is 60 seconds if not specified.
# poll_interval_seconds = 60
